[[windows]]
name = "Internet Explorer"
icon = "https://win98icons.alexmeub.com/icons/png/msie1-2.png"
add_to_desktop = [0, 0]
content = "Internet Exploruvu!!!"

[[windows]]
name = "My Computer"
icon = "https://win98icons.alexmeub.com/icons/png/computer_explorer-5.png"
add_to_desktop = [2, 1]
content = "My <i>uwoepic</i> COMPUTER!!!"