banners = [
	{ src = "banner/1.gif", link = "youareourluckyvisitor.com" },
	{ src = "banner/2.gif", link = "takethisquirqyquiz.com/homo" },
	{ src = "banner/5.gif", link = "geometryfactzz.net/hyper" },
	{ src = "banner/6.gif", link = "youareourluckyvisitor.com" },
	{ src = "banner/7.gif", link = "youareourluckyvisitor.com" },
	{ src = "banner/8.gif", link = "haremonline.se" },
	{ src = "banner/11.gif", link = "haremonline.se" },
	{ src = "banner/14.gif", link = "www.prowebb.com" },
	{ src = "banner/15.gif", link = "geometryfactzz.net/brahmagupta" },
	{ src = "banner/16.png", link = "joinus.mil.gov" },
	{ src = "banner/18.gif", link = "haremonline.se" },
	{ src = "banner/19.gif", link = "geometryfactzz.net/bretschneider" },
	{ src = "banner/20.gif", link = "fanfactions.net" },
	{ src = "banner/21.gif", link = "haremonline.se" },
	{ src = "banner/22.gif", link = "blueadaptersshop.com" },
	{ src = "banner/23.gif", link = "contact.cos.com" },
	{ src = "banner/24.gif", link = "epicdinner.com" },
]
boxes = [
	{ src = "box/3.gif", link = "#" },
	{ src = "box/4.gif", link = "haremonline.se" },
	{ src = "box/9.gif", link = "overleafpatronsolutions.com" },
	{ src = "box/10.gif", link = "usmissilesussr.com" },
	{ src = "box/12.gif", link = "fanfactions.net/fics/7399375007106807793-0" },
	{ src = "box/13.gif", link = "www.betterconnection.com/download" },
	{ src = "box/17.gif", link = "womensolvers.com/join" },
]