[[users]]
name = "Stalin"
pic = "@img:crt.png"
id = 1
[[users]]
name = "Kreiger Drömfjäll"
pic = ""
id = 3
[[users]]
name = "Leo Nètri"
pic = ""
id = 4
[[users]]
name = "Robert Fridén (MOD)"
pic = ""
id = 6
[[users]]
name = "Sunne Runeson"
pic = ""
id = 5
[[users]]
name = "Sil Frid"
pic = ""
id = 2

# ========== fic1
[[fics]]
title = "Counting the seconds since your death."
authorid = 2
date = "2001/07/01"
fandom = "Snemro Kuggas"
tags = ["Sad", "Death", "Suicide", "First Fic", "I don't know how to tag"]
summary = "You were supposed to be together now, they had promised it with all that they had. And even though you knew they were lying—you had just smiled, and they’d smiled back. And then they’d been gone."
language = "English"
views = 120
category = "Book"

[[fics.chapters]]
start_notes = "Enjoy!!"
end_notes = "Hi, this is my first time writing anything on here, so I don't really know how to do all of this stuff. Hope you enjoy! Any feedbakc is greatly appreciated!!!"
text = """<div><p>You waited. You knew it was in vain, yet you waited still. Maybe if you waited for just another minute, they would come back. You knew they wouldn’t, not in some subconscious, deep-down kind of way—you had accepted it even before your trek here—but as you stood before the grave of flowers, counting the seconds was the only thing keeping you together.</p><p>1</p><p>2</p><p>3</p><p>4…</p><p>You were supposed to be together now, they had promised it with all that they had. And even though you knew they were lying—you had just smiled, and they’d smiled back. And then they’d been gone.</p><p>5</p><p>6</p><p>7</p><p>8…</p><p>You forced your head to the side, having to vocalize your ever-counting tally to keep steady; god why did this have to be so fucking hard!? You had known it would turn out like this from the beginning.</p><p>9</p><p>10</p><p>11</p><p>12…</p><p>You almost didn’t stutter as you saw their body resting against the wall. They had been thoughtful enough to place themselves behind a pillar; not that it really did anything, but it was the thought that counted. You almost laughed as you stared at the dried red liquid staining their arms; where had they even gotten a knife from?</p><p>13</p><p>14</p><p>15</p><p>…</p><p>You lost count.</p><p>“Haha… ha… heh… god I’m pathetic…” Much to your dismay, your voice—usually all too bright and chirpy—sounded broken and choked, like you were crying. But you weren’t crying. You were <i>not</i> crying over this.</p><p>…</p><p>Tears mixed with dried blood, rehumidifying it, as you desperately clung on to what remained of them. You found yourself whispering all sorts of things—confessions, prayers, pleadings—into their all-to-pale ear. It mostly came out as a jumbled mess of sobs and stuttering.</p><p>…</p><p>You tasted blood as you bit into your lip, way too hard. The pain grounded you, forced you to face the reality of the situation: you needed to go, or people would worry about you. But you didn’t want to go. You wanted to stay here. You felt a need to bite down harder.</p><p>…</p><p>An hour had passed, maybe two. It was dark out now, fresh night air wafting down, promising to preserve them for as long as the moon stood high. You stood up.</p><p>And walked away.</p><p>…</p><p>A lone child lay behind an ornate pillar, underground. A single golden flower from the nearby flower patch beckoned them, and soon they lay under a starry night sky.</p></div>"""
[[fics.chapters.comments]]
user = 1
text = "ayo what the fuck is this shit. how bad are you at writing lol. come back when you have something worth publishing"
[[fics.chapters.comments]]
user = 3
text = "This is clearly against rule 5. Kindly delete this before I report you to the mods."
[[fics.chapters.comments]]
user = 3
text = "I would also like to add that yor write like a cunt. Get a grip on grammer and prose before you attempt something like this again, because this is just terrible!"
[[fics.chapters.comments]]
user = 2
text = "Hi Dromfjall! I appriciate your feedback, but I can't find a delete button? Sorry! Also, could you tell me how to improve my writing this is my first time here"
[[fics.chapters.comments]]
user = 4
text = "Just kill yourself already, get it over with, no one wants you on this planet, die, fuck you, when people look at you, they see sickness and disease and decay because that's all you are a curse a plight on you parents, no one every thanks you in earnest they're just so disgusted by your voice that they can't bear to hear it cry so they opt to shut you up"
[[fics.chapters.comments]]
user = 1
text = "yo leo, whasup?"
[[fics.chapters.comments]]
user = 4
text = "Oh just giving our dear guest the introduction that they deserve"
[[fics.chapters.comments]]
user = 3
text = "Maybe you could tone it down a bit? Some of the mods might misinterpret what you're saying if you're not careful. It's a miracle you're still not banned XDXD"
[[fics.chapters.comments]]
user = 3
text = """To answer your question, "Mr. Frid", I have a few things to point out:<br>
1) I don't know if your a native speaker, but you certanly don't seem like one. Your punctuation and sense for flow both suck my balls.<br>
2) Please proof read before posting. This is at best an early draft, and there are some really awkward phrases 
- " You knew they wouldn’t, not in some subconscious, deep-down kind of way—you had accepted it even before your trek here—but as you stood before the grave of flowers, counting the seconds was the only thing keeping you together."
This sucks ass.<br>
3) Don't write about subjects like su*c*de. Su*c*de is a serious issue that demands proper care. You're deranged ramblings do not qualify as such,
and by writing something like this, you are quite literally contributing to the degredation of the mental health of young people reading your work.
Ideally, stop writing about such subject entirely, as you ostensibly can not understand basic human psychology.
<hr>
I'll post more if you want
"""
[[fics.chapters.comments]]
user = 5
text = """ "human psychology"??? Really now Drömfjäll? You better stop bullshitting new users (this goes FOR ALL OF YOU) or I'll get real mad. This is
decent first attempt at a fic, I think. Not anything great, but what matters is that you start writing! After that, you're just going to get better.
<br><br>
Please ignore the users above, Sil Frid, they are bunch of idiots.
With kindest regards, Sunne
"""
[[fics.chapters.comments]]
user = 4
text = "FUUUKK off bitch, no one likes you, no one cares about you, you almost act like a moderator buthow did your application go oh right, they didnt even bothjer to spit at it because your just THAT bad at writing, so make sure to kill yourself on the way out we don't want you here"
[[fics.chapters.comments]]
user = 6
text = "Tone it down a bit Leo, will you?"
[[fics.chapters.comments]]
user = 5
text = """Oh sure thing, boss!"""
[[fics.chapters.comments]]
user = 6
text = "I'm locking this from futher posts beacuse I think we've gone a little off topic."